<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2aOrhp1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2aOrhp1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2aOrhp1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2aOrhp1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2aOrhp1\App_KernelDevDebugContainer([
    'container.build_hash' => '2aOrhp1',
    'container.build_id' => '2cb9e37e',
    'container.build_time' => 1656921925,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2aOrhp1');
